theme: jekyll-theme-minimal
title:  Jekyll Carbon 29 2
description: The Jekyll Carbon 29 2 is Cannondale's top of the line trail bike.  
  
  Table of Contents:
  1. 
  2.
  3.
  4.
  5.
  
  
  
author: "Sam Prewitt"
version=: 0.11
logo: compLogo.jpg

show_downloads: true

