theme: jekyll-theme-minimal
title: Canyon Spectral
description: The Spectral 29 CF 9 is Canyon's top of the line All Mountain Bike.
author: "Sam Prewitt"
version=: 0.11
logo: full_2021_spectral-cf-29-9-us_2831_rd-bk_P5.png

show_downloads: true
