theme: jekyll-theme-minimal
title: Jekyll Carbon 29 2\n
description: The Jekyll Carbon 29 2 is Cannondale's top of the line trail bike.  \n
author: "Sam Prewitt"
version=: 0.11
logo: compLogo.jpg

show_downloads: true

