theme: jekyll-theme-minimal
title: Cannondale Jekyll
description: The Jekyll Carbon 29 2 is Cannondale's top of the line trail bike.
author: "Sam Prewitt"
version=: 0.11
logo: logo.png

show_downloads: true
hehe using jekyll to document the jekyll
