theme: jekyll-theme-minimal
title: Cannondale Jekyll 29
description: The Jekyll Carbon 29 2 is Cannondale's top of the line enduro bike.
author: "Sam Prewitt"
version=: 0.11
logo: C20_C21200M_Jekyll_CrbAl_2_CAS_PD.png

show_downloads: true
