theme: jekyll-theme-minimal
title: logo2.jpg
description: The Jekyll Carbon 29 2 is Cannondale's top of the line trail bike.
author: "Sam Prewitt"
version=: 0.11
logo: logo2.jpg

show_downloads: true
